apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Spring-Initializr
  annotations:
    github.com/project-slug: bishwajitroy484/Spring-Initializr
spec:
  type: other
  lifecycle: unknown
  owner: guests